version: "2.3"
services:
    clean_architecture:
        image: clean-architecture:latest
        container_name: app_api
        ports:
            - 9090:9090
        depends_on:
            mysql:
                condition: service_healthy

        volumes:
           - ./config.json:/app/config.json
    mysql:
        image: mysql:5.7
        container_name: clean_architecture_mysql
        command: mysqld --user=root
        ports:
            - 3306:3306
        volumes:
            - ./app.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_USER=user
            - MYSQL_PASSWORD=mypassword
            - MYSQL_ROOT_PASSWORD=root
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    adminer:
        image: adminer
        container_name: clean_architecture_sql_admin
        restart: always
        ports:
            - 8080:8080
