// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-search-service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string               `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string               `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username             string               `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type StoreRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{1}
}

func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (m *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(m, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *StoreRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type StoreResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreResponse) Reset()         { *m = StoreResponse{} }
func (m *StoreResponse) String() string { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()    {}
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{2}
}

func (m *StoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreResponse.Unmarshal(m, b)
}
func (m *StoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreResponse.Marshal(b, m, deterministic)
}
func (m *StoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreResponse.Merge(m, src)
}
func (m *StoreResponse) XXX_Size() int {
	return xxx_messageInfo_StoreResponse.Size(m)
}
func (m *StoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreResponse proto.InternalMessageInfo

func (m *StoreResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *StoreResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type UpdateRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type UpdateResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{4}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type DeleteResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type SearchByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Api                  string   `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByNameRequest) Reset()         { *m = SearchByNameRequest{} }
func (m *SearchByNameRequest) String() string { return proto.CompactTextString(m) }
func (*SearchByNameRequest) ProtoMessage()    {}
func (*SearchByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{7}
}

func (m *SearchByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByNameRequest.Unmarshal(m, b)
}
func (m *SearchByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByNameRequest.Marshal(b, m, deterministic)
}
func (m *SearchByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByNameRequest.Merge(m, src)
}
func (m *SearchByNameRequest) XXX_Size() int {
	return xxx_messageInfo_SearchByNameRequest.Size(m)
}
func (m *SearchByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByNameRequest proto.InternalMessageInfo

func (m *SearchByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchByNameRequest) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *SearchByNameRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchByNameRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type SearchByNameResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPage             int64    `protobuf:"varint,2,opt,name=nextPage,proto3" json:"nextPage,omitempty"`
	Api                  string   `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByNameResponse) Reset()         { *m = SearchByNameResponse{} }
func (m *SearchByNameResponse) String() string { return proto.CompactTextString(m) }
func (*SearchByNameResponse) ProtoMessage()    {}
func (*SearchByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{8}
}

func (m *SearchByNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByNameResponse.Unmarshal(m, b)
}
func (m *SearchByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByNameResponse.Marshal(b, m, deterministic)
}
func (m *SearchByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByNameResponse.Merge(m, src)
}
func (m *SearchByNameResponse) XXX_Size() int {
	return xxx_messageInfo_SearchByNameResponse.Size(m)
}
func (m *SearchByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByNameResponse proto.InternalMessageInfo

func (m *SearchByNameResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SearchByNameResponse) GetNextPage() int64 {
	if m != nil {
		return m.NextPage
	}
	return 0
}

func (m *SearchByNameResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type SearchInput struct {
	ScrollId             string   `protobuf:"bytes,1,opt,name=scrollId,proto3" json:"scrollId,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	From                 int64    `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	Api                  string   `protobuf:"bytes,5,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchInput) Reset()         { *m = SearchInput{} }
func (m *SearchInput) String() string { return proto.CompactTextString(m) }
func (*SearchInput) ProtoMessage()    {}
func (*SearchInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{9}
}

func (m *SearchInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchInput.Unmarshal(m, b)
}
func (m *SearchInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchInput.Marshal(b, m, deterministic)
}
func (m *SearchInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchInput.Merge(m, src)
}
func (m *SearchInput) XXX_Size() int {
	return xxx_messageInfo_SearchInput.Size(m)
}
func (m *SearchInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchInput.DiscardUnknown(m)
}

var xxx_messageInfo_SearchInput proto.InternalMessageInfo

func (m *SearchInput) GetScrollId() string {
	if m != nil {
		return m.ScrollId
	}
	return ""
}

func (m *SearchInput) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchInput) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchInput) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchInput) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type SearchRequest struct {
	SearchInput          *SearchInput `protobuf:"bytes,1,opt,name=searchInput,proto3" json:"searchInput,omitempty"`
	Api                  string       `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{10}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetSearchInput() *SearchInput {
	if m != nil {
		return m.SearchInput
	}
	return nil
}

func (m *SearchRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type SearchResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalHits            int64    `protobuf:"varint,2,opt,name=totalHits,proto3" json:"totalHits,omitempty"`
	TookInMillis         int64    `protobuf:"varint,3,opt,name=tookInMillis,proto3" json:"tookInMillis,omitempty"`
	ScrollId             string   `protobuf:"bytes,4,opt,name=scrollId,proto3" json:"scrollId,omitempty"`
	TimedOut             bool     `protobuf:"varint,5,opt,name=timedOut,proto3" json:"timedOut,omitempty"`
	Next                 int64    `protobuf:"varint,6,opt,name=next,proto3" json:"next,omitempty"`
	Api                  string   `protobuf:"bytes,7,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0185cc5cb19188, []int{11}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SearchResponse) GetTotalHits() int64 {
	if m != nil {
		return m.TotalHits
	}
	return 0
}

func (m *SearchResponse) GetTookInMillis() int64 {
	if m != nil {
		return m.TookInMillis
	}
	return 0
}

func (m *SearchResponse) GetScrollId() string {
	if m != nil {
		return m.ScrollId
	}
	return ""
}

func (m *SearchResponse) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *SearchResponse) GetNext() int64 {
	if m != nil {
		return m.Next
	}
	return 0
}

func (m *SearchResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*StoreRequest)(nil), "proto.StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "proto.StoreResponse")
	proto.RegisterType((*UpdateRequest)(nil), "proto.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "proto.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
	proto.RegisterType((*SearchByNameRequest)(nil), "proto.SearchByNameRequest")
	proto.RegisterType((*SearchByNameResponse)(nil), "proto.SearchByNameResponse")
	proto.RegisterType((*SearchInput)(nil), "proto.SearchInput")
	proto.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "proto.SearchResponse")
}

func init() { proto.RegisterFile("user-search-service.proto", fileDescriptor_2e0185cc5cb19188) }

var fileDescriptor_2e0185cc5cb19188 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0x62, 0x3b, 0x4d, 0x26, 0x6d, 0x04, 0xdb, 0x20, 0x19, 0x53, 0xa9, 0x21, 0xa7, 0x5e,
	0x9a, 0x8a, 0x40, 0x25, 0xae, 0x2d, 0x48, 0x90, 0x03, 0x3f, 0x72, 0xa8, 0x38, 0x6f, 0xe3, 0x4d,
	0xb0, 0xb0, 0xbd, 0xee, 0xee, 0x1a, 0x1a, 0x1e, 0x83, 0x77, 0xe1, 0x49, 0x78, 0x21, 0xb4, 0xbf,
	0x8e, 0x43, 0xa4, 0xa2, 0x72, 0xf2, 0xfc, 0xec, 0xe7, 0x6f, 0xe6, 0xdb, 0x99, 0x85, 0xc7, 0x15,
	0x27, 0xec, 0x94, 0x13, 0xcc, 0x16, 0x5f, 0x4e, 0x39, 0x61, 0xdf, 0xd2, 0x05, 0x99, 0x94, 0x8c,
	0x0a, 0x8a, 0x02, 0xf5, 0x89, 0x8e, 0x57, 0x94, 0xae, 0x32, 0x72, 0xa6, 0xbc, 0xeb, 0x6a, 0x79,
	0x26, 0xd2, 0x9c, 0x70, 0x81, 0xf3, 0x52, 0x9f, 0x1b, 0xff, 0x6c, 0x83, 0x7f, 0xc5, 0x09, 0x43,
	0x03, 0x68, 0xa7, 0x49, 0xd8, 0x1a, 0xb5, 0x4e, 0x7a, 0x71, 0x3b, 0x4d, 0xd0, 0x11, 0xf4, 0x96,
	0x29, 0xe3, 0xa2, 0xc0, 0x39, 0x09, 0xdb, 0x2a, 0x5c, 0x07, 0x50, 0x04, 0xdd, 0x0c, 0x9b, 0xa4,
	0xa7, 0x92, 0xce, 0x47, 0x43, 0x08, 0x48, 0x8e, 0xd3, 0x2c, 0xf4, 0x55, 0x42, 0x3b, 0x12, 0x21,
	0xab, 0x55, 0x88, 0x40, 0x23, 0xac, 0x2f, 0x73, 0x25, 0xe6, 0xfc, 0x3b, 0x65, 0x49, 0xd8, 0xd1,
	0x39, 0xeb, 0xa3, 0x97, 0xd0, 0x5b, 0x30, 0x82, 0x05, 0x49, 0x2e, 0x44, 0xb8, 0x37, 0x6a, 0x9d,
	0xf4, 0xa7, 0xd1, 0x44, 0x77, 0x35, 0xb1, 0x5d, 0x4d, 0x3e, 0xd9, 0xae, 0xe2, 0xfa, 0xb0, 0x44,
	0x56, 0x65, 0x62, 0x90, 0xdd, 0xbb, 0x91, 0xee, 0xf0, 0xf8, 0x02, 0xf6, 0xe7, 0x82, 0x32, 0x12,
	0x93, 0x9b, 0x8a, 0x70, 0x81, 0x8e, 0xc1, 0x97, 0xb5, 0x2a, 0x75, 0xfa, 0xd3, 0xbe, 0x46, 0x4f,
	0xa4, 0x6c, 0xb1, 0x4a, 0xa0, 0x07, 0xe0, 0xe1, 0x32, 0x35, 0x32, 0x49, 0x73, 0x7c, 0x09, 0x07,
	0xe6, 0x17, 0xbc, 0xa4, 0x05, 0x27, 0xf7, 0xfc, 0xc7, 0x95, 0xaa, 0xe9, 0x3f, 0xea, 0x78, 0x05,
	0x03, 0xfb, 0x8f, 0xfb, 0x17, 0xf2, 0x0c, 0x0e, 0x5e, 0x93, 0x8c, 0xd4, 0x85, 0x6c, 0x0f, 0xcb,
	0xdf, 0x90, 0x29, 0x0c, 0x2c, 0xc4, 0xf0, 0xde, 0x8d, 0xc1, 0x70, 0x38, 0x57, 0xb3, 0x7c, 0xb9,
	0x7e, 0x8f, 0x73, 0x47, 0x86, 0xc0, 0x57, 0x53, 0xa3, 0xa1, 0xca, 0x96, 0xe0, 0xa2, 0xca, 0x15,
	0xd8, 0x8b, 0xa5, 0x29, 0x4f, 0xf1, 0xf4, 0x87, 0x9e, 0x46, 0x2f, 0x56, 0xb6, 0xa5, 0xf0, 0x6b,
	0x8a, 0x15, 0x0c, 0x9b, 0x14, 0xa6, 0xb8, 0xa7, 0x10, 0xc8, 0xde, 0x79, 0xd8, 0x1a, 0x79, 0xdb,
	0xaa, 0xe8, 0x8c, 0x1c, 0xd2, 0x82, 0xdc, 0x8a, 0x8f, 0x78, 0x45, 0x0c, 0xaf, 0xf3, 0x2d, 0x91,
	0x57, 0x13, 0xad, 0xa1, 0xaf, 0x89, 0x66, 0x45, 0x59, 0x09, 0x09, 0xe6, 0x0b, 0x46, 0xb3, 0x6c,
	0x66, 0x25, 0x70, 0xbe, 0xdc, 0x97, 0x9b, 0x8a, 0xb0, 0xb5, 0x91, 0x42, 0x3b, 0x3b, 0xfb, 0x41,
	0xe0, 0x2f, 0x19, 0xcd, 0x55, 0x43, 0x5e, 0xac, 0x6c, 0x4b, 0x1d, 0xd4, 0xd4, 0x9f, 0xe1, 0x40,
	0x53, 0x5b, 0x01, 0x5f, 0x40, 0x9f, 0xd7, 0xb5, 0x98, 0x8b, 0x47, 0xa6, 0xc5, 0x8d, 0x2a, 0xe3,
	0xcd, 0x63, 0x3b, 0xee, 0xe7, 0x77, 0x0b, 0x06, 0xf6, 0xcf, 0xff, 0xae, 0xdb, 0x11, 0xf4, 0x04,
	0x15, 0x38, 0x7b, 0x9b, 0x0a, 0x6e, 0x84, 0xab, 0x03, 0x68, 0x0c, 0xfb, 0x82, 0xd2, 0xaf, 0xb3,
	0xe2, 0x5d, 0x9a, 0x65, 0x29, 0x37, 0xed, 0x36, 0x62, 0x0d, 0xf1, 0xfc, 0x2d, 0xf1, 0x22, 0xe8,
	0xca, 0x27, 0x2d, 0xf9, 0x50, 0x09, 0xa5, 0x41, 0x37, 0x76, 0xbe, 0x1a, 0x1c, 0x72, 0x2b, 0xd4,
	0x93, 0xe2, 0xc5, 0xca, 0xb6, 0x5d, 0xed, 0xb9, 0xae, 0xa6, 0xbf, 0xda, 0xf0, 0x50, 0xd6, 0xab,
	0x3b, 0x9b, 0xeb, 0x57, 0x14, 0x9d, 0x43, 0x47, 0xef, 0x0d, 0x1a, 0xda, 0x9e, 0x36, 0x57, 0x31,
	0x7a, 0xb4, 0x15, 0x35, 0x7a, 0x4c, 0x21, 0x50, 0x6b, 0x8f, 0x0e, 0xad, 0xbc, 0x1b, 0xef, 0x48,
	0x34, 0x6c, 0x06, 0x0d, 0xe6, 0x1c, 0x3a, 0x7a, 0x55, 0x1c, 0x55, 0x63, 0xd9, 0x1c, 0xd5, 0xd6,
	0x3e, 0xbd, 0x81, 0xfd, 0xcd, 0x51, 0x46, 0x51, 0xe3, 0x42, 0x1b, 0x2b, 0x14, 0x3d, 0xd9, 0x99,
	0xab, 0xf9, 0x75, 0xdc, 0xf1, 0x37, 0xc6, 0xc7, 0xf1, 0x37, 0xaf, 0xfe, 0xba, 0xa3, 0xa2, 0xcf,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xee, 0x16, 0x01, 0x68, 0x85, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSearchServiceClient is the client API for UserSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSearchServiceClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	SearchByName(ctx context.Context, in *SearchByNameRequest, opts ...grpc.CallOption) (*SearchByNameResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type userSearchServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserSearchServiceClient(cc *grpc.ClientConn) UserSearchServiceClient {
	return &userSearchServiceClient{cc}
}

func (c *userSearchServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/proto.UserSearchService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSearchServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, "/proto.UserSearchService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSearchServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.UserSearchService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSearchServiceClient) SearchByName(ctx context.Context, in *SearchByNameRequest, opts ...grpc.CallOption) (*SearchByNameResponse, error) {
	out := new(SearchByNameResponse)
	err := c.cc.Invoke(ctx, "/proto.UserSearchService/SearchByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSearchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/proto.UserSearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSearchServiceServer is the server API for UserSearchService service.
type UserSearchServiceServer interface {
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	SearchByName(context.Context, *SearchByNameRequest) (*SearchByNameResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

// UnimplementedUserSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserSearchServiceServer struct {
}

func (*UnimplementedUserSearchServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserSearchServiceServer) Store(ctx context.Context, req *StoreRequest) (*StoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedUserSearchServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedUserSearchServiceServer) SearchByName(ctx context.Context, req *SearchByNameRequest) (*SearchByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchByName not implemented")
}
func (*UnimplementedUserSearchServiceServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterUserSearchServiceServer(s *grpc.Server, srv UserSearchServiceServer) {
	s.RegisterService(&_UserSearchService_serviceDesc, srv)
}

func _UserSearchService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearchServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSearchService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearchServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSearchService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearchServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSearchService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearchServiceServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSearchService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearchServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSearchService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearchServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSearchService_SearchByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearchServiceServer).SearchByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSearchService/SearchByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearchServiceServer).SearchByName(ctx, req.(*SearchByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserSearchService",
	HandlerType: (*UserSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _UserSearchService_Update_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _UserSearchService_Store_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserSearchService_Delete_Handler,
		},
		{
			MethodName: "SearchByName",
			Handler:    _UserSearchService_SearchByName_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _UserSearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user-search-service.proto",
}
